import { createClient, type RealtimeChannel } from "@supabase/supabase-js";
import { useCallback, useEffect, useRef, useState } from "react";
import type { PublicRoomState } from "../lib/game/online-types";
import { GAME_CONSTANTS } from "../lib/game/types";
import type { PlaylistSummary, SpotifyProfile } from "../types/spotify";

type Source = { type: "own" | "public" | "saved"; playlistId?: string; sourceName: string };
type ApiError = { message?: string };
async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); if (!response.ok) { const body = await response.json().catch((): ApiError => ({})); throw new Error(body.message ?? "We couldn't complete that request."); } return response.json() as Promise<T>; }
function roomCode(value: string): string { return value.toUpperCase().replace(/[^A-Z2-9]/g, "").slice(0, 6); }
function remainingTime(startedAt: number | null, now: number): string { return ((Math.max(0, GAME_CONSTANTS.ROUND_DURATION_MS - (now - (startedAt ?? now))) / 1000)).toFixed(1); }

export function OnlineQuiz({ onBack }: { onBack: () => void }) {
  const [profile, setProfile] = useState<SpotifyProfile | null>(null); const [ready, setReady] = useState(false); const [room, setRoom] = useState<PublicRoomState | null>(null); const [code, setCode] = useState(""); const [source, setSource] = useState<Source>({ type: "saved", sourceName: "Liked Songs" }); const [rounds, setRounds] = useState(10); const [playlists, setPlaylists] = useState<PlaylistSummary[] | null>(null); const [loading, setLoading] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void request<SpotifyProfile>("/api/spotify/profile").then(setProfile).catch(() => setProfile(null)).finally(() => setReady(true)); }, []);
  async function create() { setLoading("create"); setError(null); try { const created = await request<PublicRoomState>("/api/game/rooms", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source: source.type, playlistId: source.playlistId, sourceName: source.sourceName, rounds }) }); setRoom(created); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create the room."); } finally { setLoading(null); } }
  async function join() { if (code.length !== 6) { setError("Enter the six-character room code."); return; } setLoading("join"); setError(null); try { setRoom(await request<PublicRoomState>(`/api/game/rooms/${code}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "join" }) })); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not join that room."); } finally { setLoading(null); } }
  async function loadPlaylists() { setLoading("playlists"); try { setPlaylists(await request<PlaylistSummary[]>("/api/spotify/playlists")); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load playlists."); } finally { setLoading(null); } }
  if (!ready) return <main className="screen center"><p className="eyebrow">ONLINE MODE</p><h1>Checking your Spotify session…</h1></main>;
  if (!profile) return <main className="screen center"><p className="eyebrow">ONLINE MODE</p><h1>Spotify login required.</h1><p className="lead">Online games use your Spotify identity to keep your room membership and reconnect you safely.</p><a className="button primary" href="/api/auth/login">Log in with Spotify</a><button className="text-button" onClick={onBack}>Back</button></main>;
  if (room) return <OnlineRoom room={room} onState={setRoom} onLeave={() => setRoom(null)} />;
  return <main className="screen"><header className="topbar"><a className="brand" href="/">GUESSTIFY</a><button className="text-button" onClick={onBack}>Back to solo</button></header><section className="setup online-setup"><p className="eyebrow">ONLINE MODE</p><h1>Start a room. Bring your people.</h1><p className="lead">Your Spotify identity keeps you connected. Share the room code, then start when everyone arrives.</p>{error && <div className="notice error" role="alert">{error}</div>}<div className="online-columns"><section><h2>Create a room</h2><div className="source-actions"><button className={`button secondary ${source.type === "saved" ? "selected" : ""}`} onClick={() => setSource({ type: "saved", sourceName: "Liked Songs" })}>Liked songs</button><button className="button secondary" disabled={loading !== null} onClick={() => void loadPlaylists()}>{loading === "playlists" ? "Loading…" : "Your playlists"}</button></div>{playlists && <div className="online-playlists">{playlists.map((playlist) => <button className={`playlist ${source.playlistId === playlist.id ? "selected" : ""}`} onClick={() => setSource({ type: "own", playlistId: playlist.id, sourceName: playlist.name })} key={playlist.id}><span><strong>{playlist.name}</strong><small>{playlist.trackCount} tracks</small></span></button>)}</div>}<label>Rounds<select value={rounds} onChange={(event) => setRounds(Number(event.target.value))}><option value={5}>5 rounds</option><option value={10}>10 rounds</option><option value={15}>15 rounds</option></select></label><button className="button primary" disabled={loading !== null} onClick={() => void create()}>{loading === "create" ? "Preparing room…" : "Create room"}</button></section><section className="join-room"><h2>Join a room</h2><label htmlFor="room-code">Room code</label><input id="room-code" value={code} onChange={(event) => setCode(roomCode(event.target.value))} placeholder="A7KQ9M" maxLength={6} /><button className="button secondary" disabled={loading !== null} onClick={() => void join()}>{loading === "join" ? "Joining…" : "Join room"}</button></section></div></section></main>;
}

function OnlineRoom({ room, onState, onLeave }: { room: PublicRoomState; onState: (state: PublicRoomState) => void; onLeave: () => void }) {
  const [now, setNow] = useState(0); const [error, setError] = useState<string | null>(null); const channel = useRef<RealtimeChannel | null>(null);
  const refresh = useCallback(async () => { try { onState(await request<PublicRoomState>(`/api/game/rooms/${room.code}`)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not refresh room state."); } }, [onState, room.code]);
  useEffect(() => { const timer = window.setInterval(() => { setNow(Date.now()); void refresh(); }, 2_000); return () => window.clearInterval(timer); }, [refresh]);
  useEffect(() => { const url = import.meta.env.PUBLIC_SUPABASE_URL; const key = import.meta.env.PUBLIC_SUPABASE_PUBLISHABLE_KEY; if (!url || !key) return; const client = createClient(url, key, { auth: { persistSession: false } }); channel.current = client.channel(`room:${room.roomId}`).on("broadcast", { event: "state" }, () => { void refresh(); }).subscribe(); return () => { if (channel.current) void client.removeChannel(channel.current); }; }, [refresh, room.roomId]);
  async function action(body: object) { setError(null); try { onState(await request<PublicRoomState>(`/api/game/rooms/${room.code}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) })); } catch (caught) { setError(caught instanceof Error ? caught.message : "That action could not be completed."); } }
  async function leave() { if (!window.confirm("Leave this online game? Your current progress will be lost.")) return; try { await fetch(`/api/game/rooms/${room.code}`, { method: "DELETE" }); onLeave(); } catch { setError("Could not leave the room. Try again."); } }
  const isHost = room.hostPlayerId === room.you.playerId;
  return <main className="game-screen online-room"><header className="game-header"><a className="brand" href="/">GUESSTIFY</a><button className="text-button" onClick={() => void leave()}>Leave game</button></header>{error && <div className="notice error" role="alert">{error}</div>}<OnlinePlayers room={room} />{room.phase === "LOBBY" ? <section className="online-lobby"><p className="eyebrow">ROOM CODE</p><h1>{room.code}</h1><p>Share this code with your friends. {room.players.length} player{room.players.length === 1 ? "" : "s"} connected.</p>{isHost ? <button className="button primary" onClick={() => void action({ action: "start" })}>Start game</button> : <p className="waiting">Waiting for the host to start…</p>}</section> : <OnlineRound room={room} now={now} onAnswer={(trackId) => void action({ action: "answer", trackId })} />}</main>;
}

function OnlinePlayers({ room }: { room: PublicRoomState }) { return <div className="player-strip" aria-label="Online players">{room.players.map((player) => <div className={player.id === room.you.playerId ? "active" : ""} key={player.id}><span className="player-avatar">{player.displayName.charAt(0).toUpperCase()}</span><span><strong>{player.displayName}{player.id === room.hostPlayerId ? " · Host" : ""}</strong><small>{player.connected ? `${player.score.toLocaleString()} pts` : "Reconnecting…"}</small></span></div>)}</div>; }
function OnlineRound({ room, now, onAnswer }: { room: PublicRoomState; now: number; onAnswer: (trackId: string) => void }) { const question = room.question; if (!question) return null; if (room.phase === "ROUND_RESULT") return <section className="party-round-result"><p className="eyebrow">ROUND COMPLETE</p><h1>{room.revealedAnswer?.title ?? "Answer revealed"}</h1><p className="lead">{room.revealedAnswer?.artist ?? ""} was the answer.</p><div className="round-answers">{room.results?.map((result) => { const player = room.players.find((candidate) => candidate.id === result.playerId); return <div className={result.isCorrect ? "round-answer correct" : "round-answer wrong"} key={result.playerId}><span>{player?.displayName ?? "Player"}</span><b>{result.isCorrect ? `+${result.score}` : "+0"}</b></div>; })}</div><p className="waiting">Next round is starting…</p></section>; if (room.phase === "FINISHED") return <section className="party-round-result"><p className="eyebrow">GAME COMPLETE</p><h1>Final scores</h1><div className="round-answers">{[...room.players].sort((a, b) => a.rank - b.rank || a.displayName.localeCompare(b.displayName)).map((player) => <div className="round-answer" key={player.id}><span>#{player.rank} · {player.displayName}<small>{player.correctAnswers}/{room.totalRounds} correct · {player.accuracy}% accuracy · {player.averageResponseTime?.toFixed(2) ?? "—"}s avg</small></span><b>{player.score.toLocaleString()}</b></div>)}</div></section>; return <section className="question"><div className={`timer ${Number(remainingTime(room.roundStartedAt, now)) <= 3 ? "urgent" : ""}`}>{remainingTime(room.roundStartedAt, now)}<small>seconds</small></div><p className="eyebrow">ROUND {room.currentRound + 1}/{room.totalRounds}</p><h1>{room.you.hasAnswered ? "Answer locked." : "Name that track."}</h1>{room.you.hasAnswered ? <p className="waiting">Your answer is in. Waiting for everyone else or the timer.</p> : <div className="answers">{question.choices.map((choice, index) => <button className="answer" key={choice.trackId} onClick={() => onAnswer(choice.trackId)}><span>{String.fromCharCode(65 + index)}</span><strong>{choice.title}</strong><small>{choice.artist}</small></button>)}</div>}</section>; }
