import type { APIRoute } from "astro";
import { getRoom, joinRoom, leaveRoom, startRoom, submitRoomAnswer } from "../../../../lib/multiplayer/rooms";
import { getProfile } from "../../../../lib/spotify/api";
import { errorResponse, requireUserSession } from "../../../../lib/spotify/route";

async function identity(context: Parameters<APIRoute>[0]) { const session = await requireUserSession(context); const profile = await getProfile(session.accessToken); return { spotifyId: profile.id, displayName: profile.displayName, avatarUrl: profile.imageUrl }; }
function code(value: string | undefined): string | null { return value && /^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{6}$/i.test(value) ? value.toUpperCase() : null; }
export const GET: APIRoute = async (context) => { try { const roomCode = code(context.params.code); if (!roomCode) return Response.json({ code: "INVALID_INPUT", message: "Enter a valid room code." }, { status: 400 }); return Response.json(await getRoom(roomCode, await identity(context))); } catch (error) { return errorResponse(error); } };
export const POST: APIRoute = async (context) => { try { const roomCode = code(context.params.code); if (!roomCode) return Response.json({ code: "INVALID_INPUT", message: "Enter a valid room code." }, { status: 400 }); const body: unknown = await context.request.json(); const action = body && typeof body === "object" ? (body as { action?: unknown; trackId?: unknown }).action : null; const user = await identity(context); if (action === "join") return Response.json(await joinRoom(roomCode, user)); if (action === "start") return Response.json(await startRoom(roomCode, user)); if (action === "answer" && typeof (body as { trackId?: unknown }).trackId === "string") return Response.json(await submitRoomAnswer(roomCode, user, (body as { trackId: string }).trackId)); return Response.json({ code: "INVALID_INPUT", message: "That room action is not valid." }, { status: 400 }); } catch (error) { return errorResponse(error); } };
export const DELETE: APIRoute = async (context) => { try { const roomCode = code(context.params.code); if (!roomCode) return Response.json({ code: "INVALID_INPUT", message: "Enter a valid room code." }, { status: 400 }); await leaveRoom(roomCode, await identity(context)); return new Response(null, { status: 204 }); } catch (error) { return errorResponse(error); } };
